### ISSUE TITLE
[question] Calculation of Tscale

### ISSUE THREAD

**Issue by ShamirC** [Timothy-W-Hilton/VPRMLandSfcModel#2]
Hi Hilton, 

I have a question about the calculation of Tscale. In UrbanVPRM, the temperature T is air temperature modified by urban heat island (T_UHI). I can't tell the difference of T and T_UHI. Could you please explain what's the difference when prepare the temperature data for VPRM and UrbanVPRM. 

Cheers,
Chen

**Comment by Timothy-W-Hilton** [comment]
Hi @ShamirC,

Relative to VPRM, urbanVPRM simply replaces the temperature term T in Tscale (eq. 6 in Mahadevan et al 2008) with T_UHI, the heat-island-adjusted temperature.  The revised urbanVPRM Tscale equation is written out in SI eqn 5 in Hardiman et al 2017.  Hardiman et al 2017 Supplementary Information section S2.3 provides some more discussion - essentially, the adjustment acknowledges that urban areas tend to be slightly warmer than their less urbanised surroundings, and this affects both photosynthesis and respiration.  Hardiman et al calculate that adjustment as a function of impervious surface area (ISA) by regressing temperature against ISA for a number of stations in Massachusetts, USA; Supplementary Information section S2.2 discusses this.

Note that urbanVPRM uses the same adjustment in the temperature term in the respiration equation (Hardiman et al 2017 Supplementary Information section S2.4).

REFERENCES

Hardiman, B. S., Wang, J. A., Hutyra, L. R., Gately, C. K., Getson, J. M., & Friedl, M. A. (2017). Accounting for urban biogenic fluxes in regional carbon budgets. Science of The Total Environment, 592, 366–372. https://doi.org/https://doi.org/10.1016/j.scitotenv.2017.03.028

Mahadevan, P., Wofsy, S. C., Matross, D. M., Xiao, X., Dunn, A. L., Lin, J. C., et al. (2008). A satellite-based biosphere parameterization for net ecosystem CO2 exchange: Vegetation photosynthesis and respiration model (VPRM). Global Biogeochemical Cycles, 22, GB2005. doi:10.1029/2006GB002735

**Comment by ShamirC** [comment]
It becomes clear! 
Hardimant et al adjust the NARR 3-hourly 2m air temperature data by the regressing coefficient of ISA against measured air temperature in 25 field sites. 
But another question occurs to me, does it mean that the NARR air temperature data do not observe the temperature rise caused by urban heat island?

Thank you so much!

**Comment by Timothy-W-Hilton** [comment]
@ShamirC, glad that helped!  As for NARR, I'm not a UHI expert. The spatial resolution is "approximately 0.3 degrees (32km)" - see https://psl.noaa.gov/data/gridded/data.narr.html.  At 32 km resolution I doubt you'd see much UHI effect in the NARR data.  Maybe a little bit for some of the world's largest cities?

I'll close this issue as resolved now, but feel free to reopen or start a new one if you disagree.

**Comment by ShamirC** [comment]
Thanks so much, it is really helpful !
